fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: PC_COALESCE_DB_PRODUCTION
    schema: PUBLIC
name: Production
type: Environment
